[package]
name = "pda2cfg"
version = "1.3.0"
authors = ["ZeWaka <zewakagamer@gmail.com>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
pest = "2.1.3"
pest_derive = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snafu = "0.6"
